# Generated by Django 3.2.3 on 2021-06-21 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento2',
            name='imagens_evento',
        ),
        migrations.AddField(
            model_name='imagens',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.evento2'),
        ),
    ]
