# Generated by Django 3.2.3 on 2021-06-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20210621_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagens',
            name='evento',
        ),
        migrations.AddField(
            model_name='evento2',
            name='imagens',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.imagens'),
        ),
    ]
