# Generated by Django 3.2.3 on 2021-06-29 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20210621_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.RemoveField(
            model_name='evento2',
            name='artistas',
        ),
        migrations.RemoveField(
            model_name='evento2',
            name='images',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='data_projeto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='duracao_projeto',
        ),
        migrations.AddField(
            model_name='evento2',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.projeto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='artistas',
            field=models.CharField(default='', max_length=64),
        ),
    ]
