# Generated by Django 3.2.3 on 2021-06-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20210629_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='evento',
            field=models.ManyToManyField(to='eventos.Evento2', verbose_name='titulo_evento'),
        ),
    ]
