# Generated by Django 3.2.3 on 2021-06-29 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_alter_projeto_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='evento',
        ),
        migrations.AddField(
            model_name='evento2',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.projeto'),
        ),
    ]
