# Generated by Django 3.2.3 on 2021-06-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_auto_20210629_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='titulo_projeto',
            field=models.CharField(default='', max_length=64),
        ),
    ]
