# Generated by Django 3.2.3 on 2021-06-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_alter_projeto_titulo_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='video_projeto',
        ),
        migrations.AddField(
            model_name='evento2',
            name='video_evento',
            field=models.ManyToManyField(to='eventos.Videos'),
        ),
    ]
