# Generated by Django 3.2.3 on 2021-06-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_auto_20210630_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento2',
            name='video_evento',
            field=models.ManyToManyField(blank=True, to='eventos.Videos'),
        ),
    ]
