# Generated by Django 3.2.3 on 2021-07-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_alter_evento2_video_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='descricao_projeto',
        ),
        migrations.AddField(
            model_name='projeto',
            name='notas',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='projeto',
            name='programa',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
