# Generated by Django 3.2.3 on 2021-07-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_auto_20210710_1219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
