# Generated by Django 3.2.3 on 2021-09-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_imagens_canvas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canvas',
            old_name='id',
            new_name='nome',
        ),
    ]
