# Generated by Django 3.2.3 on 2021-09-04 15:17

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_rename_id_canvas_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canvas',
            old_name='nome',
            new_name='id_canvas',
        ),
        migrations.RemoveField(
            model_name='canvas',
            name='canvas',
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='canvas',
        ),
        migrations.CreateModel(
            name='ImagensCanvas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas', cloudinary.models.CloudinaryField(max_length=255, verbose_name='canvas')),
                ('canvasFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.canvas')),
            ],
        ),
    ]
