# Generated by Django 3.2.3 on 2021-09-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0019_auto_20210909_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento2',
            name='artistas',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='evento2',
            name='descricao_evento',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='evento2',
            name='local',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='evento2',
            name='titulo_evento',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='autores',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='notas',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='programa',
            field=models.TextField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo_projeto',
            field=models.CharField(default='', max_length=200),
        ),
    ]
