# Generated by Django 3.2.3 on 2021-09-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0020_auto_20210910_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento2',
            name='descricao_evento',
            field=models.TextField(default='', max_length=20000),
        ),
    ]
