"""
Django settings for arabesco project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""


from environs import Env  # novo

env = Env()  # novo
env.read_env()  # novo

import cloudinary
import cloudinary.uploader
import cloudinary.api


import os
import django_heroku
import dj_database_url
from decouple import config



from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = ['https://afternoon-bayou-71739.herokuapp.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'arabesco',
    'utilizadores',
    'eventos',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_installed_apps_command',
    'django_filters',
    'bootstrap4',
    'widget_tweaks',
    'django_heroku',
    'easy_pdf',
    'django_yarnpkg',
 
]

MEDIA_URL = '/media/'
MEDIA_ROOT = 'media/'



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
]

#teste commit

ROOT_URLCONF = 'arabesco.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'eventos/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

TEMPLATE_LOADERS = (
    "django.template.loaders.filesystem.Loader",
    "django.template.loaders.app_directories.Loader",
)

WSGI_APPLICATION = 'arabesco.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
#
DATABASES = {
    'default': env.dj_db_url("DATABASE_URL"), 
        'ENGINE': 'django.db.backends.postgresql_psycopg2',                #---------> DESCOMENTAR PARA DAR DEPLOY <------------
        'NAME': 'd2s1b9lknpgc4o',
        'HOST': 'ec2-35-170-85-206.compute-1.amazonaws.com',
        'PORT': '5432',                    
        'USER': 'dlymrlqxncaxht',
        'PASSWORD': '203087df6d4afab5b64f47f3167a43768565ec9f33e2624b723dd4afaf539af1',                             
    
}


DATABASES['default'] = dj_database_url.config()     #   DESCOMENTAR PARA DAR DEPLOY

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static",  'eventos/templates/static', ]

STATICFILES_STORAGE ='whitenoise.storage.CompressedManifestStaticFilesStorage',    #  DESCOMENTAR PARA DAR DEPLOY


STATIC_ROOT = os.path.join(BASE_DIR, 'static') # DESCOMENTAR PARA DAR DEPLOY

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    'django_yarnpkg.finders.NodeModulesFinder',

]

MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage'
NODE_MODULES_ROOT = os.path.join(BASE_DIR, 'node_modules')


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'goncalomatos007@gmail.com'
EMAIL_HOST_PASSWORD = 'SUpertramp007'
EMAIL_PORT = 465


django_heroku.settings(locals())       #DESCOMENTAR PARA DAR DEPLOY


cloudinary.config( 
  cloud_name = "da7qp20ja", 
  api_key = "835922641349356", 
  api_secret = "qt3MG0N2omjL_7kS_khMi7k5_1c" 
)

